## Making the Final Dataset- Correlation between safety and average stays

In [46]:
import pandas as pd

In [47]:
numbeo_dataset = pd.read_csv("../Data/combined_numbeo_dataset_adjusted.csv")
tourism_dataset = pd.read_csv("../Data/tourism_combined_data.csv")

In [48]:
combined_df_inner = pd.merge(tourism_dataset,numbeo_dataset, on="Country", how="inner")
combined_df_inner

,Code,Country,tourism_employment_per_1000_over_time,food_employment_per_1000_over_time,tourism_gdp_percentage_over_time,business_to_personal_ratio_over_time,avg_stay_days_over_time,inbound_arrivals_over_time,domestic_tourists_over_time,inbound_to_outbound_ratio_over_time,...,Crime Index_crime_index,Safety Index_crime_index,Health Care Index_health_care_index,Pollution Index_pollution_index,Quality of Life Index_quality_of_life_index,Climate Index_quality_of_life_index,Traffic Index_traffic_index,Time Index(in minutes)_traffic_index,Inefficiency Index_traffic_index,CO2Emission Index_traffic_index
0,ALB,Albania,15.608840,NaN,NaN,0.021680,2.562741,1793.802738,NaN,NaN,...,44.7,55.3,48.2,77.0,104.3,86.4,114.7,36.7,105.7,1492.0
1,DZA,Algeria,7.411779,NaN,1.129921,1.764563,1.621484,NaN,NaN,NaN,...,52.6,47.4,54.5,63.9,NaN,NaN,NaN,NaN,NaN,NaN
2,AGO,Angola,2.439200,0.710283,NaN,0.111823,4.000000,2.001969,NaN,6.428571,...,66.3,33.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ARG,Argentina,28.270541,11.444930,1.890788,0.140625,2.552286,16.460292,645.361734,0.420933,...,63.4,36.6,68.0,50.8,118.0,98.3,175.4,43.8,190.9,4039.3
4,AUS,Australia,21.464763,7.825559,1.572674,0.280377,2.216665,247.324185,3157.386095,NaN,...,47.3,52.7,73.4,26.8,192.2,93.8,163.0,37.4,237.8,6245.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,GBR,United Kingdom,42.262480,21.678139,2.069407,0.269532,2.170238,116.426500,1830.795881,NaN,...,48.3,51.7,72.7,40.7,174.5,87.2,134.2,34.7,157.4,4112.9
85,USA,United States,13.763542,3.456045,2.875489,0.160518,NaN,69.200533,NaN,0.612504,...,49.2,50.8,67.8,36.7,188.8,78.5,151.1,32.9,234.2,7302.8
86,URY,Uruguay,35.711428,14.620641,7.188250,0.084674,4.496567,913.040069,1685.925742,1.462021,...,52.0,48.0,68.6,43.5,139.8,98.0,150.7,39.5,163.3,3590.9
87,UZB,Uzbekistan,1.545283,NaN,NaN,0.021544,2.551356,NaN,NaN,NaN,...,27.9,72.1,NaN,54.0,NaN,NaN,NaN,NaN,NaN,NaN
88,ZMB,Zambia,4.312599,NaN,NaN,0.642594,3.843949,29.262606,NaN,NaN,...,45.6,54.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
combined_df_inner.drop(columns=["Rent Index_cost_of_living_index", "Crime Index_crime_index", "CO2Emission Index_traffic_index"], inplace=True)

In [50]:
combined_df_inner.columns

Index(['Code', 'Country', 'tourism_employment_per_1000_over_time',
       'food_employment_per_1000_over_time',
       'tourism_gdp_percentage_over_time',
       'business_to_personal_ratio_over_time', 'avg_stay_days_over_time',
       'inbound_arrivals_over_time', 'domestic_tourists_over_time',
       'inbound_to_outbound_ratio_over_time',
       'Cost of Living Index_cost_of_living_index',
       'Groceries Index_cost_of_living_index',
       'Restaurant Price Index_cost_of_living_index',
       'Safety Index_crime_index', 'Health Care Index_health_care_index',
       'Pollution Index_pollution_index',
       'Quality of Life Index_quality_of_life_index',
       'Climate Index_quality_of_life_index', 'Traffic Index_traffic_index',
       'Time Index(in minutes)_traffic_index',
       'Inefficiency Index_traffic_index'],
      dtype='object')

In [51]:
combined_df_inner["inverse_inefficiency_index"] = 1 / combined_df_inner["Inefficiency Index_traffic_index"]
combined_df_inner["inverse_commute_time_index"] = 1 / combined_df_inner["Time Index(in minutes)_traffic_index"]
combined_df_inner["inverse_traffic_index"] = 1 / combined_df_inner["Traffic Index_traffic_index"]
combined_df_inner["inverse_pollution_index"] = 1 / combined_df_inner["Pollution Index_pollution_index"]

healthcare vs safety - correlation - Mara
climate vs quality of living - Roxana
average stay vs safety  - Irina
food related workers vs restaurant prices -

In [52]:
#We want to determine the correlation between average stay and safety
#before normalization
correlation = combined_df_inner['avg_stay_days_over_time'].corr(combined_df_inner['Safety Index_crime_index'])
print('Correlation between average stay days and safety is:', correlation)

Correlation between average stay days and safety is: -0.25864677481022824

In [62]:
#let's normalize the data from the two columns since there are different ranges

# Drop rows where 'Safety Index_crime_index' has NaN values
combined_df_inner = combined_df_inner.dropna(subset=['Safety Index_crime_index'])
# Drop rows where 'avg_stay_days_over_time' has NaN values
combined_df_inner = combined_df_inner.dropna(subset=['avg_stay_days_over_time'])


columns_to_normalize = ['Safety Index_crime_index', 'avg_stay_days_over_time']
#normalize the two columns with min-max method
combined_df_inner[columns_to_normalize] = combined_df_inner[columns_to_normalize].apply(lambda x: (x-x.min())/(x.max()-x.min()))                                                    
correlation = combined_df_inner['avg_stay_days_over_time'].corr(combined_df_inner['Safety Index_crime_index'])
print('Correlation between average stay days and safety after data normalization is:', correlation)

Correlation between average stay days and safety after data normalization is: -0.25864677481022796

In [ ]:
#Based on the result of the correlation, the two columns are not correlated.